### ISSUE TITLE
Data preprocessing pipeline

### ISSUE THREAD

**Issue by ducnx** [mmcdermott/comprehensive_MTL_EHR#3]
Thank you for releasing the source code. 
Will you provide the extraction code for the eICU extraction system and the code for splitting each dataset? Also, is there any other parts of the data preprocessing pipeline that haven't been released, except for MIMIC-Extract?

**Comment by mmcdermott** [comment]
Hi @ducnx 

Apologies for the delay in responding! In the future, please feel free to nudge repeatedly or email me directly @ mmd@mit.edu to ensure you get a response.

We have released the eICU extraction code we use, though it is not as polished as a "full release" just yet. You can see it here: https://github.com/MLforHealth/MIMIC_Extract/tree/eICU_Extract, and I'm happy to help debug any issues you encounter using it. If there is a lot of interest by the community, we'll put in more effort to formalize the code and improve usability, so please let me know if this would be of value to you. There shouldn't be any significant parts of the data preprocessing pipelines that aren't released, but if you're curious about something specific, let me know and I can help point you to the right place.
