### ISSUE TITLE
Would you like to share the code of eICU extraction system

### ISSUE THREAD

**Issue by jingge326** [mmcdermott/comprehensive_MTL_EHR#6]
Dear author,

Thanks very much for this meaningful work! I found in the paper (A Comprehensive EHR Timeseries Pre-training Benchmark) that you mentioned “Extraction code for our eICU extraction system will be released publicly after publication.” However, I haven’t found the code yet. Would you like to share that part of the code? Thanks!

**Comment by bnestor** [comment]
Part of it is in this branch here if you are still interested: https://github.com/MLforHealth/MIMIC_Extract/tree/eICU_Extract I think the rotations and splits were generated in another notebook. But if you are looking to branch this off into another project, that eicu extract branch should be sufficient.
